# Generated by Django 5.1.5 on 2025-02-11 13:45

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(blank=True, null=True, validators=[courses.validators.validate_link]),
        ),
    ]
